on:
  # push:
  #   branches: [master]
  workflow_dispatch:
    inputs:
      os:
        description: 'macos version'
        required: false
        type: choice
        default: 'macos-14'
        options:
          - macos-13
          - macos-14
          - macos-15
      platform:
        description: 'choose a platform for compile'
        required: false
        type: choice
        default: 'all'
        options:
          - apple
          - android
          - all
          - ios
          - tvos
          - macos
  pull_request:
    branches: [master]

name: Create all library Release

jobs:
  build:
    name: compile all libs for ${{ inputs.platform }} then deploy
    runs-on: ${{ inputs.os }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: true
        local-cache: false
    - name: Checkout code
      uses: actions/checkout@v4
    - name: One Step
      run: |
        echo '------compile unibreak------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh unibreak ${{ inputs.platform }}
        echo '------compile fribidi------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh fribidi ${{ inputs.platform }}
        echo '------compile freetype------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh freetype ${{ inputs.platform }}
        if [[ ${{ inputs.platform }} == android ]]; then
          echo '------compile android fontconfig------------------------------------'
          rm -rf build || git reset --hard || git pull origin
          .github/workflows/install-dependencies.sh fontconfig android
          .github/workflows/onestep.sh fontconfig android
        fi
        echo '------compile harfbuzz------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/install-dependencies.sh harfbuzz ${{ inputs.platform }}
        .github/workflows/onestep.sh harfbuzz ${{ inputs.platform }}
        echo '------compile ass------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/install-dependencies.sh ass ${{ inputs.platform }}
        .github/workflows/onestep.sh ass ${{ inputs.platform }}
        echo '------compile yuv------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh yuv ${{ inputs.platform }}
        echo '------compile soundtouch------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh soundtouch ${{ inputs.platform }}
        echo '------compile opus------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh opus ${{ inputs.platform }}
        echo '------compile openssl------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh openssl ${{ inputs.platform }}
        echo '------compile dvdread------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh dvdread ${{ inputs.platform }}
        echo '------compile bluray------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/install-dependencies.sh bluray ${{ inputs.platform }}
        .github/workflows/onestep.sh bluray ${{ inputs.platform }}
        echo '------compile dav1d------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh dav1d ${{ inputs.platform }}
        echo '------compile uavs3d------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh uavs3d ${{ inputs.platform }}
        echo '------compile smb2------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh smb2 ${{ inputs.platform }}
        echo '------compile ffmpeg------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/install-dependencies.sh ffmpeg ${{ inputs.platform }}
        .github/workflows/onestep.sh ffmpeg ${{ inputs.platform }}
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
