on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Create all library Release

jobs:
  build:
    name: compile all lib then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: One Step
      run: |
        echo '------compile yuv------------------------------------'
        .github/workflows/onestep.sh yuv all
        echo '------compile soundtouch------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh soundtouch all
        echo '------compile unibreak------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh unibreak all
        echo '------compile fribidi------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh fribidi all
        echo '------compile freetype------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh freetype all
        echo '------compile harfbuzz------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        ./main.sh install -l 'freetype' -p ios     
        ./main.sh install -l 'freetype' -p tvos    
        ./main.sh install -l 'freetype' -p macos   
        ./main.sh install -l 'freetype' -p android 
        .github/workflows/onestep.sh harfbuzz all
        echo '------compile ass------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p ios 
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p tvos 
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p macos 
        ./main.sh install -l 'harfbuzz fribidi unibreak fontconfig' -p android 
        .github/workflows/onestep.sh ass all
        echo '------compile opus------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh opus all
        echo '------compile openssl------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh openssl all
        echo '------compile dvdread------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh dvdread all
        echo '------compile bluray------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh bluray all
        echo '------compile dav1d------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh dav1d all
        echo '------compile uavs3d------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh uavs3d all
        echo '------compile smb2------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        .github/workflows/onestep.sh smb2 all
        echo '------compile ffmpeg------------------------------------'
        rm -rf build || git reset --hard || git pull origin
        ./main.sh install -l 'openssl opus dav1d dvdread uavs3d smb2 bluray' -p ios    
        ./main.sh install -l 'openssl opus dav1d dvdread uavs3d smb2 bluray' -p tvos   
        ./main.sh install -l 'openssl opus dav1d dvdread uavs3d smb2 bluray' -p macos  
        ./main.sh install -l 'openssl opus dav1d dvdread uavs3d smb2 bluray' -p android
        .github/workflows/onestep.sh ffmpeg all