on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Ass

jobs:
  build:
    name: compile apple and android ass then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install denpendencies
      run: |
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p ios
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p tvos
        ./main.sh install -l 'harfbuzz fribidi unibreak' -p macos
        ./main.sh install -l 'harfbuzz fribidi unibreak fontconfig' -p android 
    - name: One Step
      run: .github/workflows/onestep.sh ass all