on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Create ffmpeg Release

jobs:
  build:
    name: compile ffmpeg then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install denpendencies
      run: |
        ./main.sh install -p android -l 'openssl opus dav1d dvdread uavs3d smb2 bluray'
        ./main.sh install -p ios   -l 'openssl opus dav1d dvdread uavs3d smb2 bluray'
        ./main.sh install -p tvos  -l 'openssl opus dav1d dvdread uavs3d smb2 bluray'
        ./main.sh install -p macos -l 'openssl opus dav1d dvdread uavs3d smb2 bluray'
    - name: One Step
      run: .github/workflows/onestep.sh ffmpeg all