on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Fontconfig

jobs:
  build:
    name: compile android fontconfig then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install denpendencies
      run: |
        ./main.sh install -p android -l 'freetype'
    - name: One Step
      run: .github/workflows/onestep.sh fontconfig android
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}