on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Create fribidi Release

jobs:
  build:
    name: compile fribidi then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: One Step
      run: .github/workflows/onestep.sh fribidi all