on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Create smb2 Release

jobs:
  build:
    name: compile smb2 then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: One Step
      run: .github/workflows/onestep.sh smb2 all
