on:
  # push:
  #   branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

name: Soundtouch

jobs:
  build:
    name: compile apple and android soundtouch then deploy
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
        local-cache: true
    - name: One Step
      run: .github/workflows/onestep.sh soundtouch all